### ISSUE TITLE
[PROJECT] Neurodocker support for FreeSurfer pipelines

### ISSUE THREAD

**Issue by pwighton** [brainhack-boston/brainhack-boston.github.io#30]
This [PR](https://github.com/ReproNim/neurodocker/pull/445) adds support to neurodocker to compile FreeSurfer from source.  It also includes a few use cases for the infant stream, petsurfer and samseg.

I'd like to expand this to include support for Tracula.  How can we create containers using neurodocker to run tracuala?  Ideally both from source and released versions.

**Comment by kabilar** [comment]
Hi @pwighton, closing for now as we are preparing for the hackathon next week, and this appears to be from last year.  Looking forward to working with you next week.  Thank you.
