### ISSUE TITLE
[PROJECT] Software for extracting functional sub-components of bundles

### ISSUE THREAD

**Issue by smeisler** [brainhack-boston/brainhack-boston.github.io#31]
Hi!

I am working on software the uses fROIs (e.g., clusters from an fMRI GLM contrast map) to constrain white matter bundles, as to isolate streamlines that are putative for the function being studied. From there, one can extract metrics along these streamlines for brain-function-behavior relationship analyses. The current repo is here: https://github.com/smeisler/fsub_extractor

While what we have right now is functional, there are still things we would like to add before our first release:
1) Adding CIFTI support. Right now we have support for volumetric (.nii.gz) and surface-mapped fROIs (.mgh/.label) using FreeSurfer, but it would be great if we could efficiently incorporate GIFTI metric maps such as those produced from a GLM on CIFTI data.
2) Making code that _generates_ streamlines between fROIs. Right now we have code that takes an existing tractogram and filters based on fROIs, but generating the streamlines obviates the step of making a tractogram (although there are other purposes for the full-brain tractogram).
3) Continuous Integration / Testing / Other Software Infrastructure.
4) Wiki / Doc Upgrading

Let me know if any of this is of interest to you!

**Comment by kabilar** [comment]
Hi @smeisler, closing for now as we are preparing for the hackathon next week and this appears to be from last year.  But feel free to reopen if you are interested in participating this year.  Thank you.
