### ISSUE TITLE
[PROJECT] Transform tractography data to HiP-CT space

### ISSUE THREAD

**Issue by kabilar** [brainhack-boston/brainhack-boston.github.io#42]
Goal
- The overarching goal is to integrate micro and meso datasets from the same brain.  For this project specifically, we are looking to transform a tractography dataset to HiP-CT space, and visualize the streamlines in [Neuroglancer](https://github.com/google/neuroglancer).

Developers will be provided with the following datasets:
1. HiP-CT ([dandiset 26, sub-I58](https://dandiarchive.org/dandiset/000026/draft/files?location=sub-I58/ses-Hip-CT/micr))
2. Diffusion MRI (NIfTI file format)
3. Tractography streamlines (`trk` file format) which are in diffusion space
4. Affine transformation between the diffusion MRI and HiP-CT spaces

**Comment by neurolabusc** [comment]
@frheault you already have Python [scripts](https://github.com/tee-ar-ex/trx-python/tree/master/scripts) to read/write/convert streamline formats. It seems like these could be combined with [dipy registration](https://dipy.org/documentation/1.1.0./examples_built/streamline_registration/) functions to provide a robust solution to this question.

**Comment by balbasty** [comment]
https://github.com/balbasty/ngtracts/blob/main/notebooks/show_tract.ipynb

<table>
<tr>
  <th> Modality </th> <th> Intensity </th> <th> + Tracts </th>
</tr>
<tr>
  <td> MRI </td>
  <td> <img width="200" alt="image" src="https://github.com/brainhack-boston/brainhack-boston.github.io/assets/7803834/dbe8d390-78c7-4203-868b-43a5fa3b2eda"> </td>
  <td> <img width="200" alt="image" src="https://github.com/brainhack-boston/brainhack-boston.github.io/assets/7803834/7e86099a-3f36-4905-98ad-311df7aec5aa"> </td>
</tr>
<tr>
  <td> HiP-CT </td>
  <td > <img width="200" alt="image" src="https://github.com/brainhack-boston/brainhack-boston.github.io/assets/7803834/18fe8ba8-7a19-4835-aa98-014273aa5dd8"> </td>
 <td> <img width="200" alt="image" src="https://github.com/brainhack-boston/brainhack-boston.github.io/assets/7803834/f5cd0c6d-a099-4a62-b633-0aa6c541087d"> </td>
</tr>
</table>

And the 3D tracts
<img width="500" alt="image" src="https://github.com/brainhack-boston/brainhack-boston.github.io/assets/7803834/563cdbe9-765d-4ae0-a9e3-86499b2dfb9f">

**Comment by kabilar** [comment]
cc @MikeSchutzman

**Comment by neurolabusc** [comment]
@kabilar this is timely, the NiiVue team has recently added support for additional formats (TT, TSF), TRX groups and have added the option to extrude streamlines as cylinders which can use custom shaders. You can [try out the live demo](https://niivue.github.io/niivue/features/tracts.dsi.html). Feel free to adapt any of these to neuroglancer.

![dti](https://github.com/brainhack-boston/brainhack-boston.github.io/assets/8930807/abdf3326-5510-4eff-adf3-ce17ccd84589)

**Comment by kabilar** [comment]
Thanks team.  Closing this issue as we have some prototypes of this solution and are preparing for the upcoming hackathon.
